<?php

namespace Database\Seeders;

use App\Models\Portofolio;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\File;

class PortofolioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clean table to avoid orphaned or deleted file references
        Portofolio::truncate();

        $items = [
            [
                'nama' => 'Asset 7@11x',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/Asset_7@11x.png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'UI/UX Interface Design - MacBook Pro 16 9',
                'kategori' => 'UI/UX & Web',
                'url' => 'assets/portofolio/MacBook_Pro_16_-_9.png',
                'deskripsi' => 'Karya portofolio visual profesional kategori UI/UX & Web oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Jersey Apparel Printing - RV 39 Palestin3 Jersey (1)',
                'kategori' => 'Jersey & Apparel',
                'url' => 'assets/portofolio/RV_39_palestin3_Jersey_(1).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Jersey & Apparel oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Ayam@2x 100',
                'kategori' => 'Packaging & Kemasan',
                'url' => 'assets/portofolio/ayam@2x-100.jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Packaging & Kemasan oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Ayam 1@2x 100',
                'kategori' => 'Packaging & Kemasan',
                'url' => 'assets/portofolio/ayam_1@2x-100.jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Packaging & Kemasan oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Desain Banner Promosi - Banner',
                'kategori' => 'Banner & Spanduk',
                'url' => 'assets/portofolio/banner.png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Banner & Spanduk oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Desain Banner Promosi - Banner (1)',
                'kategori' => 'Banner & Spanduk',
                'url' => 'assets/portofolio/banner_(1).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Banner & Spanduk oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Desain Banner Promosi - Banner (2)',
                'kategori' => 'Banner & Spanduk',
                'url' => 'assets/portofolio/banner_(2).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Banner & Spanduk oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Desain Banner Promosi - Banner (3)',
                'kategori' => 'Banner & Spanduk',
                'url' => 'assets/portofolio/banner_(3).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Banner & Spanduk oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Desain Banner Promosi - Banner (4)',
                'kategori' => 'Banner & Spanduk',
                'url' => 'assets/portofolio/banner_(4).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Banner & Spanduk oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Stand Booth Pameran - Booth',
                'kategori' => 'Booth & Stand',
                'url' => 'assets/portofolio/booth.png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Booth & Stand oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Stand Booth Pameran - Booth (2)',
                'kategori' => 'Booth & Stand',
                'url' => 'assets/portofolio/booth_(2).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Booth & Stand oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Stand Booth Pameran - Booth (3)',
                'kategori' => 'Booth & Stand',
                'url' => 'assets/portofolio/booth_(3).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Booth & Stand oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Kemasan Box Retail - Box',
                'kategori' => 'Packaging & Kemasan',
                'url' => 'assets/portofolio/box.jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Packaging & Kemasan oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Kemasan Box Retail - Box',
                'kategori' => 'Packaging & Kemasan',
                'url' => 'assets/portofolio/box.png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Packaging & Kemasan oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Kemasan Box Retail - Box (1)',
                'kategori' => 'Packaging & Kemasan',
                'url' => 'assets/portofolio/box_(1).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Packaging & Kemasan oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Kemasan Box Retail - Box (2)',
                'kategori' => 'Packaging & Kemasan',
                'url' => 'assets/portofolio/box_(2).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Packaging & Kemasan oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Kemasan Box Retail - Box (3)',
                'kategori' => 'Packaging & Kemasan',
                'url' => 'assets/portofolio/box_(3).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Packaging & Kemasan oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Kemasan Box Retail - Box (4)',
                'kategori' => 'Packaging & Kemasan',
                'url' => 'assets/portofolio/box_(4).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Packaging & Kemasan oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Kemasan Box Retail - Box (5)',
                'kategori' => 'Packaging & Kemasan',
                'url' => 'assets/portofolio/box_(5).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Packaging & Kemasan oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Kemasan Box Retail - Box (6)',
                'kategori' => 'Packaging & Kemasan',
                'url' => 'assets/portofolio/box_(6).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Packaging & Kemasan oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds.png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (1)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(1).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (1)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(1).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (10)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(10).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (11)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(11).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (12)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(12).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (13)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(13).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (14)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(14).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (15)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(15).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (16)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(16).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (17)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(17).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (18)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(18).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (19)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(19).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (2)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(2).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (2)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(2).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (20)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(20).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (21)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(21).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (22)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(22).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (23)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(23).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (24)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(24).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (3)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(3).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (3)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(3).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (4)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(4).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (4)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(4).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (5)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(5).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (5)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(5).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (6)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(6).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (7)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(7).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (8)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(8).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Social Media Feeds - Feeds (9)',
                'kategori' => 'Social Media',
                'url' => 'assets/portofolio/feeds_(9).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Social Media oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Final',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/final.png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flayer (1)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flayer_(1).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flayer (2)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flayer_(2).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer.png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (1)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(1).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (1)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(1).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (10)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(10).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (10)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(10).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (11)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(11).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (11)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(11).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (12)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(12).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (13)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(13).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (14)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(14).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (15)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(15).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (16)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(16).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (17)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(17).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (18)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(18).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (19)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(19).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (2)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(2).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (2)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(2).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (20)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(20).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (21)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(21).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (22)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(22).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (23)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(23).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (24)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(24).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (25)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(25).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (26)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(26).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (27)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(27).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (28)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(28).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (29)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(29).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (3)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(3).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (3)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(3).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (30)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(30).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (31)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(31).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (32)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(32).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (33)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(33).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (34)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(34).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (35)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(35).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (36)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(36).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (37)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(37).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (38)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(38).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (39)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(39).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (4)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(4).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (4)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(4).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (5)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(5).PNG',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (5)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(5).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (6)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(6).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (6)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(6).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (7)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(7).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (7)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(7).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (8)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(8).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (8)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(8).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (9)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(9).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Flyer & Poster Promosi - Flyer (9)',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/flyer_(9).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Label',
                'kategori' => 'Packaging & Kemasan',
                'url' => 'assets/portofolio/label.png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Packaging & Kemasan oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo.jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo.png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (1)',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(1).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (10)',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(10).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (11)',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(11).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (12)',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(12).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (13)',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(13).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (14)',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(14).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (15)',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(15).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (16)',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(16).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (17)',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(17).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (18)',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(18).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (19)',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(19).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (2)',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(2).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (2) Alt',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(2)_alt.png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (20)',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(20).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (21)',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(21).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (3)',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(3).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (3) Alt',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(3)_alt.png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (4)',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(4).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (4) Alt',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(4)_alt.png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (5)',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(5).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (6)',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(6).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (7)',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(7).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (8)',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(8).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Logo Branding - Logo (9)',
                'kategori' => 'Logo & Branding',
                'url' => 'assets/portofolio/logo_(9).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Logo & Branding oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Jersey Apparel Printing - Pakaian',
                'kategori' => 'Jersey & Apparel',
                'url' => 'assets/portofolio/pakaian.png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Jersey & Apparel oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Jersey Apparel Printing - Pakaian (1)',
                'kategori' => 'Jersey & Apparel',
                'url' => 'assets/portofolio/pakaian_(1).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Jersey & Apparel oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Jersey Apparel Printing - Pakaian (2)',
                'kategori' => 'Jersey & Apparel',
                'url' => 'assets/portofolio/pakaian_(2).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Jersey & Apparel oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Jersey Apparel Printing - Pakaian (3)',
                'kategori' => 'Jersey & Apparel',
                'url' => 'assets/portofolio/pakaian_(3).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Jersey & Apparel oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Jersey Apparel Printing - Pakaian (4)',
                'kategori' => 'Jersey & Apparel',
                'url' => 'assets/portofolio/pakaian_(4).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Jersey & Apparel oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Jersey Apparel Printing - Pakaian (5)',
                'kategori' => 'Jersey & Apparel',
                'url' => 'assets/portofolio/pakaian_(5).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Jersey & Apparel oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Jersey Apparel Printing - Pakaian (6)',
                'kategori' => 'Jersey & Apparel',
                'url' => 'assets/portofolio/pakaian_(6).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Jersey & Apparel oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Jersey Apparel Printing - Pakaian (7)',
                'kategori' => 'Jersey & Apparel',
                'url' => 'assets/portofolio/pakaian_(7).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Jersey & Apparel oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Jersey Apparel Printing - Pakaian (8)',
                'kategori' => 'Jersey & Apparel',
                'url' => 'assets/portofolio/pakaian_(8).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Jersey & Apparel oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Poster',
                'kategori' => 'Poster & Flyer',
                'url' => 'assets/portofolio/poster.png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Poster & Flyer oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Standing Pouch Packaging - Pouch (1)',
                'kategori' => 'Packaging & Kemasan',
                'url' => 'assets/portofolio/pouch_(1).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Packaging & Kemasan oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Standing Pouch Packaging - Pouch (2)',
                'kategori' => 'Packaging & Kemasan',
                'url' => 'assets/portofolio/pouch_(2).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Packaging & Kemasan oleh tim Premium Designz.',
            ],
            [
                'nama' => 'Seblak',
                'kategori' => 'Packaging & Kemasan',
                'url' => 'assets/portofolio/seblak.png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Packaging & Kemasan oleh tim Premium Designz.',
            ],
            [
                'nama' => 'UI/UX Interface Design - Ui Ux (1)',
                'kategori' => 'UI/UX & Web',
                'url' => 'assets/portofolio/ui_ux_(1).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori UI/UX & Web oleh tim Premium Designz.',
            ],
            [
                'nama' => 'UI/UX Interface Design - Ui Ux (10)',
                'kategori' => 'UI/UX & Web',
                'url' => 'assets/portofolio/ui_ux_(10).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori UI/UX & Web oleh tim Premium Designz.',
            ],
            [
                'nama' => 'UI/UX Interface Design - Ui Ux (11)',
                'kategori' => 'UI/UX & Web',
                'url' => 'assets/portofolio/ui_ux_(11).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori UI/UX & Web oleh tim Premium Designz.',
            ],
            [
                'nama' => 'UI/UX Interface Design - Ui Ux (12)',
                'kategori' => 'UI/UX & Web',
                'url' => 'assets/portofolio/ui_ux_(12).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori UI/UX & Web oleh tim Premium Designz.',
            ],
            [
                'nama' => 'UI/UX Interface Design - Ui Ux (13)',
                'kategori' => 'UI/UX & Web',
                'url' => 'assets/portofolio/ui_ux_(13).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori UI/UX & Web oleh tim Premium Designz.',
            ],
            [
                'nama' => 'UI/UX Interface Design - Ui Ux (14)',
                'kategori' => 'UI/UX & Web',
                'url' => 'assets/portofolio/ui_ux_(14).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori UI/UX & Web oleh tim Premium Designz.',
            ],
            [
                'nama' => 'UI/UX Interface Design - Ui Ux (15)',
                'kategori' => 'UI/UX & Web',
                'url' => 'assets/portofolio/ui_ux_(15).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori UI/UX & Web oleh tim Premium Designz.',
            ],
            [
                'nama' => 'UI/UX Interface Design - Ui Ux (16)',
                'kategori' => 'UI/UX & Web',
                'url' => 'assets/portofolio/ui_ux_(16).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori UI/UX & Web oleh tim Premium Designz.',
            ],
            [
                'nama' => 'UI/UX Interface Design - Ui Ux (17)',
                'kategori' => 'UI/UX & Web',
                'url' => 'assets/portofolio/ui_ux_(17).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori UI/UX & Web oleh tim Premium Designz.',
            ],
            [
                'nama' => 'UI/UX Interface Design - Ui Ux (2)',
                'kategori' => 'UI/UX & Web',
                'url' => 'assets/portofolio/ui_ux_(2).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori UI/UX & Web oleh tim Premium Designz.',
            ],
            [
                'nama' => 'UI/UX Interface Design - Ui Ux (3)',
                'kategori' => 'UI/UX & Web',
                'url' => 'assets/portofolio/ui_ux_(3).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori UI/UX & Web oleh tim Premium Designz.',
            ],
            [
                'nama' => 'UI/UX Interface Design - Ui Ux (4)',
                'kategori' => 'UI/UX & Web',
                'url' => 'assets/portofolio/ui_ux_(4).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori UI/UX & Web oleh tim Premium Designz.',
            ],
            [
                'nama' => 'UI/UX Interface Design - Ui Ux (5)',
                'kategori' => 'UI/UX & Web',
                'url' => 'assets/portofolio/ui_ux_(5).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori UI/UX & Web oleh tim Premium Designz.',
            ],
            [
                'nama' => 'UI/UX Interface Design - Ui Ux (6)',
                'kategori' => 'UI/UX & Web',
                'url' => 'assets/portofolio/ui_ux_(6).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori UI/UX & Web oleh tim Premium Designz.',
            ],
            [
                'nama' => 'UI/UX Interface Design - Ui Ux (7)',
                'kategori' => 'UI/UX & Web',
                'url' => 'assets/portofolio/ui_ux_(7).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori UI/UX & Web oleh tim Premium Designz.',
            ],
            [
                'nama' => 'UI/UX Interface Design - Ui Ux (8)',
                'kategori' => 'UI/UX & Web',
                'url' => 'assets/portofolio/ui_ux_(8).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori UI/UX & Web oleh tim Premium Designz.',
            ],
            [
                'nama' => 'UI/UX Interface Design - Ui Ux (9)',
                'kategori' => 'UI/UX & Web',
                'url' => 'assets/portofolio/ui_ux_(9).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori UI/UX & Web oleh tim Premium Designz.',
            ],
            [
                'nama' => 'UI/UX Interface Design - Uiux (1)',
                'kategori' => 'UI/UX & Web',
                'url' => 'assets/portofolio/uiux_(1).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori UI/UX & Web oleh tim Premium Designz.',
            ],
            [
                'nama' => 'UI/UX Interface Design - Uiux (2)',
                'kategori' => 'UI/UX & Web',
                'url' => 'assets/portofolio/uiux_(2).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori UI/UX & Web oleh tim Premium Designz.',
            ],
            [
                'nama' => 'X-Banner & Roll Banner - Xbanner',
                'kategori' => 'Banner & Spanduk',
                'url' => 'assets/portofolio/xbanner.png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Banner & Spanduk oleh tim Premium Designz.',
            ],
            [
                'nama' => 'X-Banner & Roll Banner - Xbanner (1)',
                'kategori' => 'Banner & Spanduk',
                'url' => 'assets/portofolio/xbanner_(1).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Banner & Spanduk oleh tim Premium Designz.',
            ],
            [
                'nama' => 'X-Banner & Roll Banner - Xbanner (1)',
                'kategori' => 'Banner & Spanduk',
                'url' => 'assets/portofolio/xbanner_(1).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Banner & Spanduk oleh tim Premium Designz.',
            ],
            [
                'nama' => 'X-Banner & Roll Banner - Xbanner (2)',
                'kategori' => 'Banner & Spanduk',
                'url' => 'assets/portofolio/xbanner_(2).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Banner & Spanduk oleh tim Premium Designz.',
            ],
            [
                'nama' => 'X-Banner & Roll Banner - Xbanner (2)',
                'kategori' => 'Banner & Spanduk',
                'url' => 'assets/portofolio/xbanner_(2).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Banner & Spanduk oleh tim Premium Designz.',
            ],
            [
                'nama' => 'X-Banner & Roll Banner - Xbanner (3)',
                'kategori' => 'Banner & Spanduk',
                'url' => 'assets/portofolio/xbanner_(3).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Banner & Spanduk oleh tim Premium Designz.',
            ],
            [
                'nama' => 'X-Banner & Roll Banner - Xbanner (3)',
                'kategori' => 'Banner & Spanduk',
                'url' => 'assets/portofolio/xbanner_(3).png',
                'deskripsi' => 'Karya portofolio visual profesional kategori Banner & Spanduk oleh tim Premium Designz.',
            ],
            [
                'nama' => 'X-Banner & Roll Banner - Xbanner (4)',
                'kategori' => 'Banner & Spanduk',
                'url' => 'assets/portofolio/xbanner_(4).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Banner & Spanduk oleh tim Premium Designz.',
            ],
            [
                'nama' => 'X-Banner & Roll Banner - Xbanner (5)',
                'kategori' => 'Banner & Spanduk',
                'url' => 'assets/portofolio/xbanner_(5).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Banner & Spanduk oleh tim Premium Designz.',
            ],
            [
                'nama' => 'X-Banner & Roll Banner - Xbanner (6)',
                'kategori' => 'Banner & Spanduk',
                'url' => 'assets/portofolio/xbanner_(6).jpg',
                'deskripsi' => 'Karya portofolio visual profesional kategori Banner & Spanduk oleh tim Premium Designz.',
            ],
        ];

        foreach ($items as $item) {
            if (File::exists(public_path($item['url']))) {
                Portofolio::create($item);
            }
        }
    }
}
